---
visualstudio2022_workloads:
  - Microsoft.VisualStudio.Workload.ManagedDesktop
  - Microsoft.VisualStudio.Workload.NativeDesktop
  - Microsoft.VisualStudio.Workload.Universal

visualstudio2022_components:
  # .NET
  - Microsoft.NetCore.Component.Runtime.6.0
  - Microsoft.NetCore.Component.Runtime.8.0
  - Microsoft.NetCore.Component.Runtime.9.0
  - Microsoft.Net.Component.4.7.2.TargetingPack
  - Microsoft.Net.Component.4.8.TargetingPack
  - Microsoft.Net.Component.4.8.SDK
  - Microsoft.Component.NetFX.Native
  - Microsoft.NetCore.Component.SDK
  # Code tools
  - Microsoft.VisualStudio.Component.NuGet
  - Microsoft.VisualStudio.Component.NuGet.BuildTools
  - Microsoft.VisualStudio.Component.Vcpkg
  # Compilers, build tools, and runtimes
  - Microsoft.Component.CodeAnalysis.SDK
  - Microsoft.VisualStudio.Component.Roslyn.Compiler
  - Microsoft.VisualStudio.Component.CppBuildInsights
  - Microsoft.VisualStudio.Component.VC.Redist.MSM
  - Microsoft.VisualStudio.Component.VC.Redist.14.Latest
  - Microsoft.VisualStudio.Component.VC.Llvm.Clang
  - Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset
  - Microsoft.VisualStudio.Component.VC.CMake.Project
  - Microsoft.VisualStudio.Component.VC.CLI.Support
  - Microsoft.VisualStudio.Component.VC.Tools.ARM
  - Microsoft.VisualStudio.Component.VC.Tools.ARM64
  - Microsoft.VisualStudio.Component.VC.Tools.x86.x64
  - Microsoft.VisualStudio.Component.VC.Runtimes.ARM.Spectre
  - Microsoft.VisualStudio.Component.VC.Runtimes.ARM64.Spectre
  - Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre
  - Microsoft.Component.VC.Runtime.UCRTSDK
  - Microsoft.VisualStudio.Component.UWP.VC.ARM64
  - Microsoft.Component.MSBuild
  # SDKs, libraries, and frameworks
  - Microsoft.VisualStudio.Component.VC.ATL.ARM
  - Microsoft.VisualStudio.Component.VC.ATL.ARM.Spectre
  - Microsoft.VisualStudio.Component.VC.ATL.ARM64
  - Microsoft.VisualStudio.Component.VC.ATL.ARM64.Spectre
  - Microsoft.VisualStudio.Component.VC.ATL
  - Microsoft.VisualStudio.Component.VC.ATL.Spectre
  - Microsoft.VisualStudio.Component.VC.MFC.ARM
  - Microsoft.VisualStudio.Component.VC.MFC.ARM.Spectre
  - Microsoft.VisualStudio.Component.VC.MFC.ARM64
  - Microsoft.VisualStudio.Component.VC.MFC.ARM64.Spectre
  - Microsoft.VisualStudio.Component.VC.ATLMFC
  - Microsoft.VisualStudio.Component.VC.ATLMFC.Spectre
  - Microsoft.VisualStudio.Component.Windows10SDK.18362
  - Microsoft.VisualStudio.Component.Windows11SDK.22621
