#!/bin/sh
set -e

debian="DEBIAN_RELEASES"
ubuntu="UBUNTU_RELEASES"
raspbian="RASPBIAN_RELEASES"

eval `grep ^ID= /etc/os-release`
eval `grep ^VERSION_ID= /etc/os-release`

if ! test "$ID" = "debian" -o "$ID" = "ubuntu" -o "$ID" = "raspbian" -o "$ID" = "linuxmint" ; then
    echo "ERROR: unable to identify OS, guessing ubuntu"
    ID="ubuntu"
fi

case "$ID" in
    "debian")
        DISTRIBUTION=debian
        CODENAME=`echo $debian | grep -o "$VERSION_ID:[a-z]\+" | cut -d: -f2`
        ;;
    "ubuntu")
        DISTRIBUTION=ubuntu
        CODENAME=`echo $ubuntu | grep -o "$VERSION_ID:[a-z]\+" | cut -d: -f2`
        ;;
    "raspbian")
        DISTRIBUTION=raspbian
        CODENAME=`echo $raspbian | grep -o "$VERSION_ID:[a-z]\+" | cut -d: -f2`
        ;;
    "linuxmint")
        DISTRIBUTION=ubuntu
        eval `grep UBUNTU_CODENAME= /etc/os-release`
        CODENAME=$UBUNTU_CODENAME
        ;;
esac

if test -z "CODENAME" ; then
    echo "ERROR: unable to identify $DISTRIBUTION version, guessing testing"
    CODENAME="testing"
fi

mkdir -p /etc/apt/sources.list.d
mkdir -p /etc/apt/trusted.gpg.d

echo "deb REPO_URL/deb/$DISTRIBUTION ${CODENAME}SNAPSHOT main" > /etc/apt/sources.list.d/REPO_NAME.list
cp -a /usr/share/REPO_NAME/REPO_NAME.gpg /etc/apt/trusted.gpg.d/REPO_NAME.gpg

#DEBHELPER#
